In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.6.0


In [3]:
scalar = torch.tensor(5)
scalar

tensor(5)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

5

In [6]:
vector = torch.tensor([3,5])
vector

tensor([3, 5])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[1,2,3],
                     [4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 3])

In [12]:
tensor = torch.tensor([[[1,2,3],
                       [4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 2, 3])

In [15]:
#random tensor
random_tensor = torch.rand(4,5)
random_tensor

tensor([[0.6150, 0.9095, 0.7563, 0.0874, 0.3641],
        [0.5786, 0.5184, 0.7261, 0.8261, 0.8387],
        [0.4115, 0.3072, 0.3828, 0.4698, 0.4955],
        [0.9598, 0.6791, 0.6972, 0.6546, 0.3783]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([4, 5])

In [18]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) #color channels (R,G,B), height, width
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [19]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
#creating a range tensors
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [22]:
#creating tensors like
ten_zeros = torch.zeros_like(one_to_ten) #or torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

## Note: 
Tensor datatype is one of the 3 big errors you'll run into PyTorch & deep learning 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [23]:
tensor_32_float = torch.tensor([2.0,4.0,6.0], dtype=None, device=None, requires_grad=False)
tensor_32_float.dtype

torch.float32

In [24]:
tensor_16_float = tensor_32_float.type(torch.float16)
tensor_16_float

tensor([2., 4., 6.], dtype=torch.float16)

In [25]:
#element wise multiplication
tensor = torch.tensor([1,2,3])
3*tensor

tensor([3, 6, 9])

In [26]:
#matrix multiplication
torch.matmul(tensor, tensor) #or torch.mm()

tensor(14)

In [27]:
#same as
tensor @ tensor

tensor(14)

In [28]:
tensor.shape

torch.Size([3])

In [29]:
torch.matmul(torch.rand(2,3), torch.rand(3,5)).shape

torch.Size([2, 5])

In [30]:
#using transpose
torch.matmul(torch.rand(2,5), torch.rand(3,5).T).shape

torch.Size([2, 3])

In [31]:
#tensor aggregation
x = torch.arange(0,100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [33]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [34]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [35]:
#torch.mean() funtion requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

## Finding the positional min, max value

In [36]:
#return index value that has min value
x.argmin()

tensor(0)

In [37]:
#return index value that has max value
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, unsqueezing tensors

In [38]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [40]:
z = x.view(1,9) #z is different view of x
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
#changing z change x because a view of a tensor shares the same memory as the original input.
z[0,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [42]:
x_stacked = torch.stack([x,x,x,x], dim=0) #stack vertical
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
torch.stack([x,x,x], dim=1) #stack horizantal

tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [44]:
# tensor.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_sq = x_reshaped.squeeze()
print(f"\nNew tensor: {x_sq}")
print(f"New shape: {x_sq.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [45]:
#tensor.unsqueeze() - adds a single dimension to target tensor at a specific dim ()
print(f"Previous tensor: {x_sq}")
print(f"Previous shape: {x_sq.shape}")

x_unsq = x_sq.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsq}")
print(f"New shape: {x_unsq.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [46]:
#tensor.permute() - rearrenges the dimensions of a target tensor to a specified order
x_original = torch.rand(size=[224,224,3]) #height, width, color channels

x_permuted = x_original.permute(2,0,1)   #color channels, height, width

print(f"Original tensor shape: {x_original.shape}")
print(f"Permuted tensor shape: {x_permuted.shape} ")

Original tensor shape: torch.Size([224, 224, 3])
Permuted tensor shape: torch.Size([3, 224, 224]) 


In [47]:
x_original[0,0,0] = 3
x_original[0,0,0], x_permuted[0,0,0] #share same memory

(tensor(3.), tensor(3.))

In [48]:
import numpy as np

array = np.arange(1.0, 10.0)  #default dtype=float64
tensor = torch.from_numpy(array) #default tensor dtype=float32, change tensor dtype to float64

array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [49]:
array = array +1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [50]:
tensor = torch.ones(8)
array = tensor.numpy()  #pytorch->numpy, changes the default dtype of array to float32
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [51]:
tensor = tensor + 1
array, tensor

(array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2., 2.]))

In [52]:
#Let's make some random but reproducible tensors
random_seed = 42
torch.manual_seed(random_seed)
rand_tensor_a = torch.rand(3,4)

torch.manual_seed(random_seed)
rand_tensor_b = torch.rand(3,4)

print(rand_tensor_a)
print(rand_tensor_b)
print(rand_tensor_a == rand_tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [53]:
torch.cuda.is_available()

False

In [54]:
matrix = torch.rand(3,5)
matrix

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854],
        [0.5739, 0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695, 0.3588]])

In [55]:
matrix.min()

tensor(0.1053)

In [56]:
matrix.max()

tensor(0.8854)

In [57]:
matrix.argmin()

tensor(12)

In [58]:
matrix.argmax()

tensor(4)

In [68]:
torch.manual_seed(7)
tensor = torch.rand(1,1,1,10)
tensor, tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [69]:
tensor = tensor.squeeze()
tensor, tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

In [70]:
tensor = tensor.unsqueeze(0)
tensor, tensor.shape

(tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
          0.8513]]),
 torch.Size([1, 10]))